### ISSUE TITLE
Ghost preview not working

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master#4]
Works if your builder is not busy. But fails to show up if your builder is currently constructing.

http://i.imgur.com/4z0F55g.png

**Comment by MNoya** [comment]
Fixed in 232d82acdad6120eeec22c875e4f06ea2caf37a7

**Comment by cowsforyou** [comment]
Issue seems to be partially fixed. I tried to manually match your edits here: https://github.com/cowsforyou/barracks_master/commit/a66d9458d9fcc9289a5b17015ba1d11ff9cdd8a4

The BH im using for BM1 is way too outdated and I think veggie made a lot of edits that makes it too intertwined that a flat replacement would just break the whole system. 

If you have some time can you help me see what's missing? I've a feeling it's just one line missing or needs to be changed.
